---
- name: "Prepare {{ ansible_facts['distribution'] }} guest operating system."
  include_tasks: "{{ ansible_facts['distribution'] | lower }}.yml"
  when: "ansible_facts['distribution'] == 'Ubuntu'"
